### PR TITLE
Add ID_PATH to DRM devices for Xorg

### PR DESCRIPTION
**Pull request by amshafer**
In create_drm_handler we add the PCI_ID udev property, but when using PRIME offloading Xorg wants to check ID_PATH in
config_udev_odev_setup_attribs. This is necessary as part of the rube goldberg auto configuration of Nvidia Optimus machines.

To get Xorg to play nice this change defines the ID_PATH property by querying the busid specified for the DRI node in question. This is done with the hw.dri.<cardnum>.busid sysctl. With this change we can define dynamic configs in xorg.conf.d and have X automatically use nvidia-drm.

### CODE REVIEW

**Comment by wulf7** [comment]
Merged. Thanks!

**Comment by amshafer** [comment]
Is there any way we can get a new release that includes this? This is needed for PRIME setups with nvidia-drm, so getting this in ports means one less thing for users to manually install when testing.

**Comment by wulf7** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270937

**Comment by wulf7** [comment]
Finally, committed: https://cgit.freebsd.org/ports/commit/?id=d1703243900b34745e428b4fdfa886bb6476d202

**Pull request merged**
